### ISSUE TITLE
STRINGLN not working after upgrade to firmware version 0.20.2

### ISSUE THREAD

**Issue by seawarrior181** [dekuNukem/duckyPad#109]
Hi,

I've learned today that the new STRINGLN command isn't working after upgrading the firmware to 0.20.2.  I make extensive use of the construct:
STRING macro text goes here
ENTER
...so I am very interested in the STRINGLN functionality.  What do I need to do to activate this command?

A snap of my duckyPad configurator v0.13.3 is included below.

![image](https://user-images.githubusercontent.com/19429380/202918295-b2d4d8f8-8bc7-48ca-844d-b92ba49c3353.png)

Notice that Code Check indicates **Error(s) found!**

Best,
Dan

**Comment by dekuNukem** [comment]
Just press `Save` anyway and it should work on the pad itself! I just haven't released the software update yet 😅

**Comment by seawarrior181** [comment]
ok, that worked, thanks.
