### ISSUE TITLE
Allow status change initiated from the computer

### ISSUE THREAD

**Issue by pjamargh** [dekuNukem/duckyPad#125]
It would be great to have a CLI app to send a status change to the Duckypad.

For example, I'd like a key color to reveal whether certain app is running or not and also change the key mapping. This can be done with a 2 state key, e.g. voice dictation on, off, but sometimes might not be in sync. This can happen if the dictation software crashes. Ideally I'd add a call on the dictation start script that will tell the Duckypad when the dictation daemon stopped, so the used key becomes 'dictation on' rather than stay on 'dictation off' function.

**Comment by jose1711** [comment]
Check out https://github.com/dekuNukem/duckyPad-profile-autoswitcher/blob/master/HID_details.md
