### ISSUE TITLE
COMMAND  triggers Invalid Command error in configurator

### ISSUE THREAD

**Issue by Deseao** [dekuNukem/duckyPad#130]
Configurator version: 1.3.0
DuckyPad Firmware: 1.2.0

Attempting to create a Script with the contents
`COMMAND R`
to refresh a website on a mac results in the configurator reporting the script as invalid.
Note that RCOMMAND is seen as valid still.

**Comment by dekuNukem** [comment]
hi there! this is a known bug that will be fixed in the next update, you can use ALT key in the meantime instead

**Comment by Deseao** [comment]
Ah thanks so much!
