### ISSUE TITLE
Release 1.6.1 does not support macOS ARM

### ISSUE THREAD

**Issue by noinfo** [dekuNukem/duckyPad#148]
The latest release shows "INTEL" and "x86" for macOS architectures. That should be the same and "ARM" is missing...

...or it is just named wrong. 

![fabian meyer-macbook_air-screenshot- 2023-10-16 at 11 56 21](https://github.com/dekuNukem/duckyPad/assets/799099/670929ef-7a55-4bd1-9d6a-e3d16954e29b)

**Comment by dekuNukem** [comment]
good catch! I have changed the name
