### ISSUE TITLE
duckypad configurator 0.13 Linux compatibility

### ISSUE THREAD

**Issue by simonCor** [dekuNukem/duckyPad#15]
Hi i just tried the configurator on linux.

It almost works. The only problem is, that you use the color name "SystemButtonFace".

This is not available on Linux. Therefore the only thing you have to be linux compatible is either replace by e.g. "grey" or use a os switch on linux.

Regards

**Comment by dekuNukem** [comment]
Thanks for letting me know! Should be a quick fix, I'll do it this week.

**Comment by dekuNukem** [comment]
done
