### ISSUE TITLE
How end an infinite loop?

### ISSUE THREAD

**Issue by asd-ez** [dekuNukem/duckyPad#150]
I need to use an infinity loop e.g.:
```
WHILE TRUE
	LMOUSE
END_WHILE
```
How can I end it by the next click by key? I try like this: 
```
LOOP1:
WHILE TRUE
	LMOUSE
END_WHILE

LOOP2:
```
What will I need to write in `LOOP2`?

**Comment by dekuNukem** [comment]
Probably something like this:

```
VAR $k = 0
BCLR
WHILE $k == 0
    RMOUSE
    DELAY 50
    $k = $_READKEY
END_WHILE
```

it press the mouse button while checking if a key is pressed in the loop. if so, it exits the loop.

**Comment by asd-ez** [comment]
@dekuNukem Thanks for your help!
