### ISSUE TITLE
Feature Request: Ability to `GOTO_PROFILE <profile_name>` rather than `GOTO_PROFILE <profile_position>`

### ISSUE THREAD

**Issue by richardgaunt** [dekuNukem/duckyPad#162]
It would be great to map profile names to profile number so you when you have a profile called `test` you can write the following:
```
GOTO_PROFILE test

```

rather than

```
GOTO_PROFILE 5
````

The reason being that you need to keep track when you change the order of your profiles and adding and removing them.

**Comment by dekuNukem** [comment]
Hi there! I think you can use `GOTO_PROFILE_NAME` command do to that, give it a try and let me know how it goes!

**Comment by richardgaunt** [comment]
Wow thanks I had missed that in the docs thank you again

**Comment by richardgaunt** [comment]
Thanks this works perfectly.
