### ISSUE TITLE
Extend duckyscript for numpad keys

### ISSUE THREAD

**Issue by madwort** [dekuNukem/duckyPad#17]
For one application I'm using, it would be useful to be able to send numpad digits as well as the regular digits (which I've been doing with e.g. `STRING 1`. 
In https://github.com/keyboardio/Chrysalis this is keyCode 30 vs keyCode 89.
Would it be possible to add to the list of modifier keys `NUMPAD_1` etc?
Thanks!

**Comment by dekuNukem** [comment]
Sure! I'll do it over this weekend.

**Comment by madwort** [comment]
Amazing, thanks!

**Comment by dekuNukem** [comment]
https://github.com/dekuNukem/duckyPad/releases/tag/0.6.0

**Comment by madwort** [comment]
works, thanks!
