### ISSUE TITLE
Instructions for flashing duckypad on macOS/linux etc

### ISSUE THREAD

**Issue by madwort** [dekuNukem/duckyPad#19]
The duckypad can now be flashed from macOS using http://dfu-util.sourceforge.net/ which can be installed using https://brew.sh/

```bash
$ brew install dfu-util
```

hold DFU button & connect duckypad, then run:

```bash
$ dfu-util --device ,0483:df11 -a 0 -D /path/to/duckypad_v0.8.0.dfu
```

**Comment by dekuNukem** [comment]
thanks for the contribution! I'll add it later today.
