### ISSUE TITLE
Switching profiles from DuckyScript

### ISSUE THREAD

**Issue by agausmann** [dekuNukem/duckyPad#26]
I'd be interested in having a DuckyScript command that switches profiles. This would be useful for a setup with "menu" profiles, where keys can be used to quickly jump between profiles.

**Comment by dekuNukem** [comment]
Good idea! I might add it once I have finished shipping all the boards.

In the meantime, you can use the profile quickswitch by holding down `+` key.

**Comment by dekuNukem** [comment]
I have added this feature in the latest firmware (0.15)

https://github.com/dekuNukem/duckyPad/blob/master/firmware_updates_and_version_history.md
