### ISSUE TITLE
Config App on macOS

### ISSUE THREAD

**Issue by clive-cli** [dekuNukem/duckyPad#28]
On macOS you use 'WINDOWS' for 'cmd' key and 'ALT' for 'Option'.

However, in the config app, neither of these trigger the correct key when tested. If the scripts are saved and the script triggered from the pad itself, it works fine.

So this is just the config apps test feature. May be worth adding a note to the readme to that effect. Certainly not the end of the world!

**Comment by verfehlix** [comment]
thanks for that hint!

**Comment by dekuNukem** [comment]
I'll look into this issue, thanks for letting me know.

**Comment by dekuNukem** [comment]
I have fixed it in the code, a new version of the software will be released shortly.
