### ISSUE TITLE
Firmware Makefile?

### ISSUE THREAD

**Issue by gregkh** [dekuNukem/duckyPad#40]
I was wanting to make some firmware changes to clean up a few tiny things I noticed, but I don't
seem to be able to find a Makefile at the root of the firmware tree that would allow me to build
the code again.

Is it just not checked in?  Any hints on how to rebuild the code would be appreciated.

**Comment by dekuNukem** [comment]
Discussed over email. Hopefully that solves the issue!

Let me know if you have further questions.

**Comment by dekuNukem** [comment]
Not sure why I went through email for this, anyway, I used Keil IDE for this project, which handles all the builds and makefiles. It is free for the STM32 chip that this uses, and I wrote a [tutorial on how to get started](https://github.com/dekuNukem/STM32_tutorials), first lesson is enough to get it set up.

**Comment by 13rac1** [comment]
Ah ha! Thanks!
