### ISSUE TITLE
Switching profile based on focused application

### ISSUE THREAD

**Issue by harryjubb** [dekuNukem/duckyPad#42]
Hi, really cool project!

Wanted to ask if it is possible to switch the selected profile based on the active application?

A use case example:

> As a programmer, I want duckyPad to be able to switch to a specific profile for VSCode snippets when I switch to VSCode, so that I can instantly have access to the macros that I need to insert snippets

**Comment by dekuNukem** [comment]
Not at the moment, but I do want to look into it in the near future.

It would be a bit tricky programming-wise, and there isn't much space left on the microcontroller, but I'll see what I can do.

**Comment by dekuNukem** [comment]
Added! try it out here:

https://github.com/dekuNukem/duckyPad-profile-autoswitcher

**Comment by harryjubb** [comment]
Amazing! Will do: thank you!
