### ISSUE TITLE
Bug in dpkm_german.txt

### ISSUE THREAD

**Issue by ExitThroughTheWire** [dekuNukem/duckyPad#46]
Hi,
I had some issues with the character ö and the german keyboard layout. It seems to be a little bug in line 260 of the dpkb_german.txt.

https://github.com/dekuNukem/duckyPad/blob/5889e752dba7bbff93237c88db0a680a2631baf3/sample_profiles/keymaps/dpkm_German.txt#L260

The correct duckcode for `0xf6` should be `0x0033`, as it is a standad character of the german keyboard layout.
May you'd like to update it in the next version.

And by the way, thanks for this really cool project!

Edit
Some typos

**Comment by dekuNukem** [comment]
Well spotted! I have updated it :)
