### ISSUE TITLE
Difficulty updating firmware on Mac

### ISSUE THREAD

**Issue by elstamey** [dekuNukem/duckyPad#47]
Similar to #45, but I am using the correct path.

> $ dfu-util --device ,0483:df11 -a 0 -D ~/Downloads/duckypad_v0.16.0.dfu
> dfu-util 0.10
> 
> Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
> Copyright 2010-2020 Tormod Volden and Stefan Schmidt
> This program is Free Software and has ABSOLUTELY NO WARRANTY
> Please report bugs to http://sourceforge.net/p/dfu-util/tickets/
> 
> dfu-util: No DFU capable USB device available

I followed the DFU boot instructions.  But the dfu-util doesn't see it at the address in the command provided.  I don't know how to find it.

When I boot normally, there is no attached ducky, so I don't know where to direct the configurator to test any change.  Am I supposed to do this with the micro sd reader?  the leds respond when I press keys, but even characters like numbers and letters do not type.  I would like to update the firmware to see if that fixes it.

**Comment by dekuNukem** [comment]
Sorted in discord, turned out to be a faulty USB cable :)
