### ISSUE TITLE
DuckyPad config v0.12.0 win10 failed to start

### ISSUE THREAD

**Issue by DikUl** [dekuNukem/duckyPad#52]
v0.11.0 working great, v0.12.0 doesn't start at all.

![v0.11.0](https://i.imgur.com/X5Uy9fB.jpg)

![v0.12.0](https://i.imgur.com/brife5D.jpg)

**Comment by dekuNukem** [comment]
I just fixed it 😅 try 0.12.1:

https://github.com/dekuNukem/duckyPad/releases/tag/0.12.1

**Comment by DikUl** [comment]
> I just fixed it 😅 try 0.12.1:
> 
> https://github.com/dekuNukem/duckyPad/releases/tag/0.12.1

That was quick 😅
