### ISSUE TITLE
Duckypad Configuration Tool thoroughly hangs windows explorer session it is launched from

### ISSUE THREAD

**Issue by DrMiaow** [dekuNukem/duckyPad#53]
I launch it and nothing happens. The windows explorer session it is launched in is totally locked up until I reboot my PC. I am using windows 10.

![image](https://user-images.githubusercontent.com/31360/118989705-28683a00-b97a-11eb-9934-a557285ea5e8.png)

Any ideas please?

**Comment by M-14K** [comment]
I had a similar issue on version 0.12.0 of duckypad.
have you downloaded the newest one 0.12.1?

**Comment by DrMiaow** [comment]
Yes. I have resolved it though. I right clicked on it and brought up properties and realised that Windows had blocked it (unsigned and downloaded from internet). I unlocked it and all good now. 

![image](https://user-images.githubusercontent.com/31360/118994109-f8229a80-b97d-11eb-9e4c-6d21c2fbfed3.png)
