### ISSUE TITLE
Feature Request: onKeyDown and onKeyUp Functionality

### ISSUE THREAD

**Issue by ImmortalZypther** [dekuNukem/duckyPad#54]
Being able to control how long keys are held down and when they are released would be incredibly useful for automating actions in games, where you typically need to hold down a key to get things done.

This is the only feature that I found was missing from DuckyScript that was present on other mainstream keyboards with macro functionality. 

The DEFAULTCHARDELAY command does this to some extent, but isn't capable of holding a key as a toggle, which could be implemented with onKeyDown, onKeyUp, and the existing LOOP function.

**Comment by dekuNukem** [comment]
added in latest beta test, give it a try and let me know if it works !

https://gist.github.com/dekuNukem/3d4ca966c83dca38ae89ee1142806ef2
