### ISSUE TITLE
Feature request: Reset loop by holding a key

### ISSUE THREAD

**Issue by jose1711** [dekuNukem/duckyPad#82]
`LOOP` command is quite useful but sometimes I am missing a way to reset the loop. I think it would be great if there was an option to reset the counter (and start from `LOOP0`) after holding the same key. As there might be use-cases where key auto-repeat is actually useful perhaps a new command `LOOPH` (loop with reset by holding) could be introduced.

**Comment by dekuNukem** [comment]
Actually there is a top secret undocumented command that does exactly that 😅

`LCR` command will reset the loop counter to 0. It was there for debugging purposes and I never removed it.

**Comment by jose1711** [comment]
Heh, interesting. Syntax checker will complain but the command indeed works. Also it's useful to know that it resets *all* counters (in all `LOOPx` commands). That means that it is useful only if a user has one key utilizing loops and at the same time can afford to sacrify another key for resets.

**Comment by asd-ez** [comment]
@jose1711 Could you tell me about how do you use this `LCR` command? I try to write like this:
```
LOOP0:
VAR $toggle = 1
WHILE $toggle == 1
	TAB 
	DELAY 100
	SHIFT 5
	DELAY 100
END_WHILE

LOOP1:
LCR 
```
But throw error `Unknown command: LCR` and I can't save this script.
