### ISSUE TITLE
Problem with a key color

### ISSUE THREAD

**Issue by mobily** [dekuNukem/duckyPad#86]
Hello @dekuNukem! I found a pretty strange issue, one key has a different color, it's green, but in the duckyPad configurator, it's set to red. Do you know what may cause this problem?

<img width="912" alt="CleanShot 2022-01-04 at 10 51 06@2x" src="https://user-images.githubusercontent.com/1467712/148041266-986a0c7c-6af9-4123-b2ad-2ed36cfa26f5.png">
<img src="https://user-images.githubusercontent.com/1467712/148041283-e5c35317-fc72-496b-b59f-86244935e12d.jpg">

**Comment by dekuNukem** [comment]
That's very strange indeed!  I wonder if the red element of that RGB LED is damaged, maybe try a few more colours and see if there is any red element on that LED at all. Maybe try a different SD card too to rule out the possibility of file corruption too.

If it is indeed a hardware issue, I can arrange a replacement.

**Comment by mobily** [comment]
@dekuNukem it started working correctly again, apparently, an SD card reformat has helped 🚀 thank you, keep it up, I love duckyPad! ❤️

**Comment by mobily** [comment]
@dekuNukem it seems to be a problem with the red element of that RGB LED, and yes, it might be damaged 😢

- works when the color is set to cyan:

<img width="300" src="https://user-images.githubusercontent.com/1467712/148060261-6d87f83b-42b6-464a-aea7-b064ae5fc5ae.jpg">

- works when it's set to blue:

<img width="300" src="https://user-images.githubusercontent.com/1467712/148060282-2c0cb8d9-4da6-44b4-8b04-630d4658b029.jpg">

- works when the color is to green:

<img width="300" src="https://user-images.githubusercontent.com/1467712/148060372-b8fedfb9-f06f-4373-8cb5-37e4301edb2c.jpg">

- doesn't work when the color is set to white, brown, purple, or red:

<img width="300" src="https://user-images.githubusercontent.com/1467712/148060420-919b40c2-0ac7-4598-aa94-79dd06a9c919.jpg">
<img width="300" src="https://user-images.githubusercontent.com/1467712/148060785-61686654-6722-4561-89aa-aec367c4ce10.jpg">
<img width="300" src="https://user-images.githubusercontent.com/1467712/148061033-ae68ecdd-1ae5-4ce4-ab3a-9feb7996cb1c.jpg">

**Comment by dekuNukem** [comment]
yeah that does look like the case, let me know your order number and I can send you another one for free.

**Comment by mobily** [comment]
thank you so much, I really appreciate that! ❤️ here's the order number: 300063

**Comment by dekuNukem** [comment]
Sure! I'll send it out tomorrow :) Same address?

**Comment by mobily** [comment]
yup, same address 😊 thank you once again!

**Comment by dekuNukem** [comment]
I have dropped it off, and it should arrive in the usual time :)

**Comment by mobily** [comment]
hey @dekuNukem, I got the new board you sent me, thanks for that! ❤️ however, seems it might be broken as well, after connecting to my mac, the SD card isn’t visible, as well as `dfu-util` doesn’t see it, keys don’t react on pressing, and the RGB backlight doesn’t work too

I have tried to use a different either USB-C cable or USB port, and literally, nothing works 😢 although, it boots up! 

![IMG_20220119_140520](https://user-images.githubusercontent.com/1467712/150136887-955c3f47-9e9b-4f76-baaf-3686be34944d.jpg)

**Comment by dekuNukem** [comment]
Hi there! Sorry to hear about the issue, it is rather unusual to have 2 of them be faulty in a row. I would suggest try holding `+` button on the duckyPad, it should go into quickswitch mode, and LEDs should be all white, see if that works. You can also try [re-formatting the SD card and copy back the sample profiles](https://github.com/dekuNukem/duckyPad/blob/master/troubleshooting.md#i-want-to-use-my-own-sd-card), or even try one of your own SD cards. It would also be helpful to try it on a different computer, a PC perhaps, or even a phone or tablet.  Let me know how it goes!

**Comment by mobily** [comment]
> it is rather unusual to have 2 of them be faulty in a row.

that's what I initially thought as well, it's simply impossible to have that bad luck 😆 

the old board → seems everything works fine, I can connect with the board via the configurator app, `dfu-util` recognizes the device, the RGB backlight works as well (excluding that one key backlight) and when I press a key, a specific action is performed on my mac

the new board → I can't connect with the board via the configurator app, `dfu-util` doesn't recognize the device, the RGB backlight is off all the time, nothing happens when I press a key, however, I can switch profiles with `+` and `-` buttons and go into the quickswitch mode

both boards are using FW 0.19.8, is there any other way to flash FW if `dfu-util` doesn't recognize the device? 

(here's the photo with both boards, the old board is on the left side, the new one is on the right)

![IMG_20220119_164756](https://user-images.githubusercontent.com/1467712/150167225-8a38c227-2a44-45e3-9a95-00b043766b3f.jpg)

**Comment by mobily** [comment]
the new board isn't listed in the connected HID devices
![image](https://user-images.githubusercontent.com/1467712/150170363-07ef4769-6287-4d41-8093-58bb703f16b6.png)
and the old one:
![image](https://user-images.githubusercontent.com/1467712/150170409-d6811adb-ab4d-4564-a85e-e2ac3c37f81a.png)

**Comment by dekuNukem** [comment]
It seems that the new duckyPad isn't getting data through, that's why it is not recognised by the PC. Perhamp you can try cleaning the pins on the USB connector as well as the pins on the microcontroller chip using a dry clean toothbrush or somthing, make sure nothing is stuck between the pins. Maybe try a different able too, but I'm sure you already did that.

Anyway, I can keep sending you more boards until it works 😅 but let's make sure first
