### ISSUE TITLE
DuckyPad OLED screen freezed when starting up PC

### ISSUE THREAD

**Issue by SnailMango** [dekuNukem/duckyPad#93]
Hello! My DuckyPad started having this issue since a couple of months.
When I startup my PC, it lights up normally, but when I try to switch profile using the - and + buttons, the screen is freezed on the first functions list. In order to make it work again, I have to disconnect and reconnect the USB cable. If I push the reset button on the side, the screen turns off and it won't work anymore if I don't disconnect and re-connect the cable.
I already tried re-flashing latest firmware and changing cable but the problem is still the same.
What can I do? I'm attaching a video of the problem.

https://user-images.githubusercontent.com/64862343/174437614-ad5e09dc-cf4d-406d-bfab-43790c2fdb29.MOV

**Comment by dekuNukem** [comment]
Hi there! Looks like the OLED screen is acting up a bit, re-seating the ribbon cable usually fixes it, you can find the instruction here:

https://github.com/dekuNukem/duckyPad/blob/master/troubleshooting.md#the-oled-screen-isnt-working-properly

let me know how it goes!

**Comment by SnailMango** [comment]
Sorry for the super old reply but I just logged back into Github and realized I forgot to reply! However it really looks that reseating the ribbon cable fiexd the screen text problem! Thanks!
