### ISSUE TITLE
Duckypad OLED went out suddenly (FW 0.20.1)

### ISSUE THREAD

**Issue by Kaos9111** [dekuNukem/duckyPad#98]
I had a strange problem today:

While I was changing the profile several times (minus button), the display suddenly went off. the buttons still worked (plus, minus and the macro buttons).

I had restarted the duckypad several times using the reset button and the usb cable. - without success

I then checked the display cable. I also unplugged it and plugged it back in. - without success

I then flashed the frmware 0.20.1 again. without success

I thought the ducky pad was broken :(

So I flashed the firmware 0.20.0 and the display suddenly went back on. after the update to 0.20.1 everything is ok.

I have tried several times to reproduce the error, I have not succeeded.

**Comment by dekuNukem** [comment]
The OLED ribbon cable sometimes gets loose, re-seating it usually fix the problem. No need to do anything if it is working though!
